### PR TITLE
WIP: SvxReflector

### PR DESCRIPTION
**Pull request by sm0svx**
Use SvxReflector to link multiple SvxLink nodes together over TCP/UDP using logic linking.

### CODE REVIEW

**Comment by f5vmr** [comment]
This looks good, I will be checking this out very soon.
Chris

**Comment by f5vmr** [comment]
Hi Again Tobias
In the final, I simply downloaded the zip, installed and compiled it as normal, modified the svxreflector.conf to the necessary parametres and set it running.
However despite the ports being open (admittedly through a dyndns alias at both ends) there appears to be only timeouts showing on both repeaters I am attempting to interface.
I am running the svxreflector on ubuntu at home and connecting through compatible ports to the network where the repeaters reside, and at the moment we need to redirect the parabola connecting the wifi on site as the throughput is not at all what it should be.
When the weather improves and we can get to the top of the building where the parabola has shifted slightly in the high winds then we can try again.
At least for the moment it is not a negative try, I will keep you posted.
 
Chris
 
 
 
 
 
> Message du 01/03/17 08:37
> De : "Tobias Blomberg" 
> A : "sm0svx/svxlink" 
> Copie à : "Subscribed" 
> Objet : [sm0svx/svxlink] SvxReflector (#254)
> 
>
> Use SvxReflector to link multiple SvxLink nodes together over TCP/UDP using logic linking.

You can view, comment on, or merge this pull request online at:
>   https://github.com/sm0svx/svxlink/pull/254
Commit Summary

Split base of Logic class into new class LogicBase
The UdpSocket::dataReceived signal provide port number
Initial revision pf the SvxReflector
MsgPack 0.5 adaptions
Add message marshal class Async::Msg
Switched out msgpack for Async::Msg marshaller
Fix warning about void pointer arithmetics
Disable debug printouts in AsyncMsg.h
Remove unused msgpack code
Debug printout cleanup
Add reconnect timer to ReflectorLogic
Add configuration for LISTEN_PORT and AUTH_KEY in SvxReflector
Reconnect on locally ordered ReflectorLogic disconnect
Fix uninitialized reflector UDP port config variable
Add and check UDP datagram sequence number
Add periodic UDP heartbeat
Add audio fifo to received reflector audio
Change config var PASSWORD to AUTH_KEY in ReflectorLogic
Check default authentication key in svxreflector
Add check multiple talkers
Add talker timeout timer

File Changes

M src/async/ChangeLog (5)
M src/async/audio/AsyncAudioDeviceUDP.cpp (3)
M src/async/audio/AsyncAudioDeviceUDP.h (3)
A src/async/core/AsyncMsg.h (631)
M src/async/core/AsyncUdpSocket.cpp (4)
M src/async/core/AsyncUdpSocket.h (3)
M src/async/core/CMakeLists.txt (2)
A src/async/demo/AsyncMsg_demo.cpp (129)
M src/async/demo/AsyncUdpSocket_demo.cpp (6)
M src/async/demo/CMakeLists.txt (2)
M src/echolib/EchoLinkDispatcher.cpp (6)
M src/echolib/EchoLinkDispatcher.h (6)
M src/echolib/EchoLinkProxy.cpp (4)
M src/echolib/EchoLinkProxy.h (6)
M src/svxlink/CMakeLists.txt (1)
A src/svxlink/reflector/CMakeLists.txt (32)
A src/svxlink/reflector/Reflector.cpp (385)
A src/svxlink/reflector/Reflector.h (187)
A src/svxlink/reflector/ReflectorClient.cpp (346)
A src/svxlink/reflector/ReflectorClient.h (198)
A src/svxlink/reflector/ReflectorMsg.h (377)
A src/svxlink/reflector/svxreflector.conf (4)
A src/svxlink/reflector/svxreflector.cpp (779)
M src/svxlink/svxlink/CMakeLists.txt (2)
A src/svxlink/svxlink/DummyLogic.h (169)
M src/svxlink/svxlink/LinkManager.cpp (38)
M src/svxlink/svxlink/LinkManager.h (12)
M src/svxlink/svxlink/Logic.cpp (23)
M src/svxlink/svxlink/Logic.h (17)
A src/svxlink/svxlink/LogicBase.cpp (142)
A src/svxlink/svxlink/LogicBase.h (225)
A src/svxlink/svxlink/ReflectorLogic.cpp (524)
A src/svxlink/svxlink/ReflectorLogic.h (203)
M src/svxlink/svxlink/svxlink.conf.in (8)
M src/svxlink/svxlink/svxlink.cpp (44)
M src/versions (5)

Patch Links:

https://github.com/sm0svx/svxlink/pull/254.patch
https://github.com/sm0svx/svxlink/pull/254.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sm0svx/svxlink","title":"sm0svx/svxlink","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sm0svx/svxlink"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"SvxReflector (#254)"}],"action":{"name":"View Pull Request","url":"https://github.com/sm0svx/svxlink/pull/254"}}}

**Comment by f5vmr** [comment]
I wonder if you have missed a line somewhere, as ReflectorLogic seems not to be compiled into /usr/share/svxlink/events.d with the rest of the Logic files. Can you confirm this? I also ask if this logic needs to be pulled into current repeater installations. In which case it won;t do it at the present time.
Regards
Chris

**Comment by dl1hrc** [comment]
occurs on a client, just receiving a packet from svxreflector:

Program received signal SIGSEGV, Segmentation fault.
0x000000000047fbe2 in sigc::internal::slot_call4<sigc::bound_mem_functor4<void, ReflectorLogic, Async::IpAddress const&, unsigned short, void*, int>, void, Async::IpAddress const&, unsigned short, void*, int>::call_it(sigc::internal::slot_rep*, Async::IpAddress const&, unsigned short const&, void* const&, int const&) ()
Missing separate debuginfos, use: zypper install alsa-plugins-debuginfo-1.0.28-3.1.3.x86_64 libasound2-debuginfo-1.0.28-6.1.4.x86_64 libgcc_s1-debuginfo-4.8.3+r212056-2.4.4.x86_64 libgcrypt20-debuginfo-1.6.1-8.19.1.x86_64 libgpg-error0-debuginfo-1.15-1.2.x86_64 libgsm1-debuginfo-1.0.13-25.1.2.x86_64 libopus0-debuginfo-1.1-2.1.2.x86_64 libpopt0-debuginfo-1.16-27.1.2.x86_64 libsigc-2_0-0-debuginfo-2.4.1-4.1.x86_64 libspeex1-debuginfo-1.1.999_1.2rc1-23.1.2.x86_64 libstdc++6-debuginfo-4.8.3+r212056-2.4.4.x86_64 tcl-debuginfo-8.6.3-6.1.x86_64

**Comment by dl1hrc** [comment]
I've running a client behind an umts router, from there I get the message:
*** WARNING: Incoming UDP packet has the wrong source UDP port number and the connection is lost.
It happens a few minutes after the start.

**Comment by f5vmr** [comment]
This looks like a failure in the install of some of the associated software? I am still waiting to hear about where the ReflectorLogic.tcl is - It never got compiled from my download.
Chris
 
 
 
 
> Message du 01/03/17 18:39
> De : "Adi Bier" 
> A : "sm0svx/svxlink" 
> Copie à : "Chris F5VMR" , "Comment" 
> Objet : Re: [sm0svx/svxlink] SvxReflector (#254)
> 
>
> occurs on a client, just receiving a packet from svxreflector:
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000000047fbe2 in sigc::internal::slot_call4, void, Async::IpAddress const&, unsigned short, void*, int>::call_it(sigc::internal::slot_rep*, Async::IpAddress const&, unsigned short const&, void* const&, int const&) ()
> Missing separate debuginfos, use: zypper install alsa-plugins-debuginfo-1.0.28-3.1.3.x86_64 libasound2-debuginfo-1.0.28-6.1.4.x86_64 libgcc_s1-debuginfo-4.8.3+r212056-2.4.4.x86_64 libgcrypt20-debuginfo-1.6.1-8.19.1.x86_64 libgpg-error0-debuginfo-1.15-1.2.x86_64 libgsm1-debuginfo-1.0.13-25.1.2.x86_64 libopus0-debuginfo-1.1-2.1.2.x86_64 libpopt0-debuginfo-1.16-27.1.2.x86_64 libsigc-2_0-0-debuginfo-2.4.1-4.1.x86_64 libspeex1-debuginfo-1.1.999_1.2rc1-23.1.2.x86_64 libstdc++6-debuginfo-4.8.3+r212056-2.4.4.x86_64 tcl-debuginfo-8.6.3-6.1.x86_64
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sm0svx/svxlink","title":"sm0svx/svxlink","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sm0svx/svxlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dl1hrc in #254: occurs on a client, just receiving a packet from svxreflector:\r\n\r\nProgram received signal SIGSEGV, Segmentation fault.\r\n0x000000000047fbe2 in sigc::internal::slot_call4\u003csigc::bound_mem_functor4\u003cvoid, ReflectorLogic, Async::IpAddress const\u0026, unsigned short, void*, int\u003e, void, Async::IpAddress const\u0026, unsigned short, void*, int\u003e::call_it(sigc::internal::slot_rep*, Async::IpAddress const\u0026, unsigned short const\u0026, void* const\u0026, int const\u0026) ()\r\nMissing separate debuginfos, use: zypper install alsa-plugins-debuginfo-1.0.28-3.1.3.x86_64 libasound2-debuginfo-1.0.28-6.1.4.x86_64 libgcc_s1-debuginfo-4.8.3+r212056-2.4.4.x86_64 libgcrypt20-debuginfo-1.6.1-8.19.1.x86_64 libgpg-error0-debuginfo-1.15-1.2.x86_64 libgsm1-debuginfo-1.0.13-25.1.2.x86_64 libopus0-debuginfo-1.1-2.1.2.x86_64 libpopt0-debuginfo-1.16-27.1.2.x86_64 libsigc-2_0-0-debuginfo-2.4.1-4.1.x86_64 libspeex1-debuginfo-1.1.999_1.2rc1-23.1.2.x86_64 libstdc++6-debuginfo-4.8.3+r212056-2.4.4.x86_64 tcl-debuginfo-8.6.3-6.1.x86_64\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/sm0svx/svxlink/pull/254#issuecomment-283412679"}}}

**Comment by sm0svx** [comment]
Nice to see you're testing this! Just realize that this is very early code. Not fully implemented. There are still features missing but I'm close. I expect it to not work flawlessly right now. I'm working on it right now.

@f5vmr, there is no ReflectorLogic.tcl. The ReflectorLogic do not need a tcl file since it does not have an event handler.

@dl1hrc, the UDP code is very untested. I'm really not sure that the concept will work. This remains to be tested. I've mostly been testing locally on a single computer. Next step is to test it gradually in more and more difficult situations, the first one being just going through a firewall both at the client and server.

Thanks again for testing!

**Comment by f5vmr** [comment]
Hi Tobias,
OK, I wondered if I had correctly followed the pattern. It should work with the same configuration that I had with Adi's SVXserver with virtual ports in my case 5210 via TYPE=Net if I'm right. But I can't confirmthat due to poor connections with the internet at the moment. My ssh connection to the repeaters is extremely s l o w ........
 
Chris
 
 
 
 
> Message du 01/03/17 20:10
> De : "Tobias Blomberg" 
> A : "sm0svx/svxlink" 
> Copie à : "Chris F5VMR" , "Mention" 
> Objet : Re: [sm0svx/svxlink] SvxReflector (#254)
> 
>
> Nice to see you're testing this! Just realize that this is very early code. Not fully implemented. There are still features missing but I'm close. I expect it to not work flawlessly right now. I'm working on it right now.
> @f5vmr, there is no ReflectorLogic.tcl. The ReflectorLogic do not need a tcl file since it does not have an event handler.
> @dl1hrc, the UDP code is very untested. I'm really not sure that the concept will work. This remains to be tested. I've mostly been testing locally on a single computer. Next step is to test it gradually in more and more difficult situations, the first one being just going through a firewall both at the client and server.
> Thanks again for testing!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sm0svx/svxlink","title":"sm0svx/svxlink","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sm0svx/svxlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sm0svx in #254: Nice to see you're testing this! Just realize that this is very early code. Not fully implemented. There are still features missing but I'm close. I expect it to not work flawlessly right now. I'm working on it right now.\r\n\r\n@f5vmr, there is no ReflectorLogic.tcl. The ReflectorLogic do not need a tcl file since it does not have an event handler.\r\n\r\n@dl1hrc, the UDP code is very untested. I'm really not sure that the concept will work. This remains to be tested. I've mostly been testing locally on a single computer. Next step is to test it gradually in more and more difficult situations, the first one being just going through a firewall both at the client and server.\r\n\r\nThanks again for testing!"}],"action":{"name":"View Pull Request","url":"https://github.com/sm0svx/svxlink/pull/254#issuecomment-283438392"}}}

**Comment by sm0svx** [comment]
@f5vmr, first please can you trim down your messages when answering via email? Only include the necessary text. The conversation in the pull request get so messy with all the text.

You should not use Net RX. You should just use the ReflectorLogic with a config that look something like this:
```
[ReflectorLogic]
TYPE=Reflector
HOST=your.reflector.host
#PORT=5300
CALLSIGN=YOURCALL
AUTH_KEY="Your password"
AUDIO_CODEC=OPUS
```

**Comment by sm0svx** [comment]
Oh, and the port to open on the server is 5300. You should not need to open any ports on the client.

**Comment by dl1hrc** [comment]
@sm0svx : It seems that the segfault is gone with your last commit :)

@f5vmr : We have complete different approaches here. The new svxreflector has nothing to do with my first attempts (svxserver)!

**Comment by sm0svx** [comment]
Ok @dl1hrc . Good that the crash disappeared even if I don't think it was due to anything I did. It looked like a build problem of some sort.

I've just done some tests here involving some firewalls. The setup is two SvxLink nodes behind the same firewall and an SvxReflector across the Internet behind another firewall. Seem to work well so far.

**Comment by dl1hrc** [comment]
ok, maybe it was my complete new installation after pulling the diff.
I'm testing with five Logics on one engine, two of them are ReflectorLogics on different ports. Think that I will have more clients next days. Have access to about ten clients, so we have a smart network for tests.

**Comment by sm0svx** [comment]
That will certainly be a hard test for the reflector :-)

Just a word of caution, there will be protocol changes which are not backwards compatible so all nodes need to be upgraded. Also, I would make sure to have TX timeout set up for all transmitters in the network or constant monitoring just in case something in the reflector logic hangs.

**Comment by dl1hrc** [comment]
it seems that the remote udp ports are changing:
01.03.2017 22:00:13.876: DM0KWD: Login OK from 82.113.121.52:6172
01.03.2017 22:00:14.117: setting RemoteUdpPort=1358
...

01.03.2017 22:04:39.092: ### DB0HRC: MsgUdpHeartbeat()
01.03.2017 22:04:48.288: ### DL1HRC: MsgUdpHeartbeat()
01.03.2017 22:05:13.983: *** WARNING: Incoming UDP packet has the wrong source UDP port number, reemoteUdpPort=1358, port=6077
01.03.2017 22:05:39.093: ### DB0HRC: MsgUdpHeartbeat()
01.03.2017 22:05:48.288: ### DL1HRC: MsgUdpHeartbeat()
01.03.2017 22:06:13.973: *** WARNING: Incoming UDP packet has the wrong source UDP port number, reemoteUdpPort=1358, port=10066
01.03.2017 22:06:39.092: ### DB0HRC: MsgUdpHeartbeat()
01.03.2017 22:06:48.288: ### DL1HRC: MsgUdpHeartbeat()
01.03.2017 22:07:13.965: *** WARNING: Incoming UDP packet has the wrong source UDP port number, reemoteUdpPort=1358, port=3336
01.03.2017 22:07:39.094: ### DB0HRC: MsgUdpHeartbeat()
01.03.2017 22:07:48.288: ### DL1HRC: MsgUdpHeartbeat()
01.03.2017 22:08:13.950: *** WARNING: Incoming UDP packet has the wrong source UDP port number, reemoteUdpPort=1358, port=11238
01.03.2017 22:08:39.093: ### DB0HRC: MsgUdpHeartbeat()
01.03.2017 22:08:48.288: ### DL1HRC: MsgUdpHeartbeat()
01.03.2017 22:09:14.317: *** WARNING: Incoming UDP packet has the wrong source UDP port number, reemoteUdpPort=1358, port=5427
...

**Comment by dl1hrc** [comment]
_Also, I would make sure to have TX timeout set up for all transmitters in the network or constant monitoring just in case something in the reflector logic hangs._
I have made my experiences with stations, which were a long time on broadcast :/ That's why I've included a timer into svxserver that send a SQL=close command to all connected stations and cuts the connection to the node if it was transmitting to long.

**Comment by dl1hrc** [comment]
If the ip address of the (dsl) client was changing either a disconnect/connect should be enforced or a message should be send by the client.

**Comment by sm0svx** [comment]
Stations that hang on squelch open is another issue and the functionality you mention also should be implemented like you describe in your manual page. Obviously it's not there yet in this early version of SvxReflector.

The problems I talk about is about the case where there are bugs in this early implementation of ReflectorLogic or the SvxReflector itself. Then a TX timeout or constant monitoring is the last line of defence.

I have not implemented TCP heartbeat messages yet and the UDP heartbeats are only used for keeping the channel through the firewall open; so at the moment there is no mechanism to detect the case where an IP address suddenly changes. This may be the next important thing for me to take a look at.

I'm a bit baffled though. The warning is about the wrong source port number but if the IP changes it should complain about that the IP address is wrong. Are you going through multiple firewalls so that the IP change is concealed when it reaches SvxReflector?

**Comment by dl1hrc** [comment]
The message of the wrong source UDP is sent by a client behind an umts router. Unfortunately it's a very unreliable connection and I've no idea what happens with that. Maybe the provider is blocking/changing some things. It's peculiarly that the router gets a "normal" public ip address, not from 10's or 192's networks.
I think much more important would be the successful reconnection after an ip address change due to dsl interrupt.

**Comment by dl1hrc** [comment]
Good work, Tobias! Looks very good. The transmission of callsigns to each node makes it easier to administrate. Do you want to include the eventhandler later?
V1.5.99.5 Installed on DB0HRC, DL2HXA, DB0FIB, DM0SVX, DB0MGN, DL1HRC (testnode).
DM0LEI, DB0EL and DB0HAL(3 nodes) will follow on monday, some nodes in Thuringia will also changed. Frank in Berlin is working on it too :)
73s de Adi / DL1HRC

**Comment by sm0svx** [comment]
You are very brave ;-)  There still are some bugs to crush. For example, there seem to be some issue with UDP sequence numbers getting out of sync for some reason. I haven't had time to look at it yet.

I did not intend to include the event handler. I cannot think of a reason to send audio clips to the reflector. Can you?
For informing external applications about events in SvxLink I'd rather work on a general event notification mechanism or possibly one could make use of the STATE_PTY as an intermediate solution.
Or did you think of another specific use-case?

**Comment by dl1hrc** [comment]
Yes, it's really brave but I think it's the best way to examine a new software or new functionality on it.
There is no problem if a hamradio repeater isn't working or faulty for a short time, no one will die because of that. It's good to see that more than five sysops here in Central Germany work together to find out remaining problems.
You're right that there is no need to send audio directly into the network. I see more application possibilities on handling with connection information (callsigns, sql=1/0, tx=on/off, maybe control commands, ...). I think the PTY's will do that.

BTW: The biggest problem at the moment is the #251, I started gdb with verbose=on but got no further information. Will create a core if possible.

vy 73s de Adi / DL1HRC

**Comment by sm0svx** [comment]
What's your thought on testing the latest version of the reflector? Does it work? Are there any features missing from SvxServer (other than SQL_TIMEOUT)? Have you found any show-stopper bugs?  There are some more work to do but I feel it's beginning to stabilize.

When the base is stable I guess there are some more features to add (talk groups? reflector<->reflector comms? reflector qsorec? reflector web audio streaming? reflector control commands?) but let's get the base stable first.

**Comment by f5vmr** [comment]
Hi,
I have now installed SvxReflector on one repeater and the server, and I have included [ReflectorLogic] in svxlink.conf, but how do I now refer to this section? Like RepeaterLogic, I included ReflectorLogic in the same line but the error appears that ReflectorLogic is referred to but not found. What have I missed?, and yes I did compile from the SvxReflector.zip. Regards, Chris

**Comment by sm0svx** [comment]
On the svxlink side you need a configuration that look something like this:
```
[GLOBAL]
LOGICS=RepeaterLogic,ReflectorLogic
LINKS=ReflectorLink

[RepeaterLogic]
...

[ReflectorLogic]
TYPE=Reflector
HOST=reflector.example.com
CALLSIGN=MYCALL
AUTH_KEY="The password"
AUDIO_CODEC=OPUS

[ReflectorLink]
CONNECT_LOGICS=RepeaterLogic:99:REF,ReflectorLogic
DEFAULT_ACTIVE=1
TIMEOUT=10
```

**Comment by f5vmr** [comment]
svxlink: symbol lookup error: svxlink: undefined symbol: _ZTIN5Async9TcpClientE

From your latest commit Tobias - Svxlink does no longer start.
Chris F5VMR

**Comment by dl1hrc** [comment]
Can not confirm the crash. Installed latest svxreflector branch here, will observe it.

**Comment by sm0svx** [comment]
@f5vmr, maybe you forgot to run "ldconfig" or you need to remove old SvxLink libs from the system, something like rm -i /usr/lib64/libasync{core,cpp,audio,qt}*. You may need to adjust the path to match your specific system. Then "make install" again.

**Comment by sm0svx** [comment]
Note: Changes in the protocol that is not compatible with previous versions of SvxReflector. All participating nodes need to be updated.

**Comment by sp2ong** [comment]
I have run on test svxreflector and connect two svxlink nodes. First is Echolink Node and the second is  svxlink smplex node on 438 Mhz without echolink module only DTMF Repeater module is defined. Interlink working very nice between svxlink.
But my question can I send DTMF code via RF 438 Mhz to execute a command on connected via svxreflector my EchoLink node ???

I have to try to send DTMF command via 438 RF with active DTMF repeater but it looks like Echolink node connected via svxreflector don't work
73 Waldek

**Comment by dl1hrc** [comment]
Am 17.05.2017 um 08:05 schrieb Waldek:
> I have run on test svxreflector and connect two svxlink nodes. First is Echolink Node and the second is svxlink smplex node on 438 Mhz without echolink module only DTMF Repeater module is defined.
> Interlink working very nice between svxlink.
> But my question can I send DTMF code via RF 438 Mhz to execute a command on connected via svxreflector my EchoLink node ???
> 
> I have to try to send DTMF command via 438 RF with active DTMF repeater but it looks like Echolink node connected via svxreflector don't work
> 73 Waldek
> 

Hi Waldek,

no, the dtmf decoder is "connected" to the local rx, not to the streamed network audio. I can't see that it will be a good idea to change that.
Introduce yourself you have running a reflector with 20 nodes connected and each node will detect the dtmf commands of all others...

73s de Adi / DL1HRC

**Comment by sp2ong** [comment]
Hi Adi,
> Introduce yourself you have running a reflector with 20 nodes connected and each node will detect >the dtmf commands of all others...

Yes, you are right it does not make sense use DTMF in this case

73 Waldek

**Comment by sp2ong** [comment]
Hi Adi and Tobias,

I am back to possibility execute DTMF command via svvxreflector. I agree with Adi when we use svxrelectror to connect different repeaters and echolink nodes. But why not add an option in ReflectroLogic for example:

Allow_DTFM=1 or 0 (default 0 disable DTMF )

Why? For example, I would like to create small sub-regional network communication use svxlink nodes. SVXReflectro is it good to do this but I don't need to create on every svxlink node echolink node. For this, it is enough setup one echolink node if anybody would like to join to our local small communication network. But it will be nice to have that any user from svxlink node can send DTMF code via DTMF repeater module to one Echolink node in this network. 

Why I prefer svxreflector because when any user speaks on one node it is retransmission on other nodes. When I have use remotetrx setup on other nodes to connect to the main node with EchoLink module users can execute DTMF command on a main Echolink node but we don't have retransmission stream from one node to others on RF. Maybe I am making mistake in configuration with remotetrx.

**Comment by dl1hrc** [comment]
Hi Waldek,

theoretically possible but it presupposes a very strict configuration environment on all involved nodes. You can only enable one MetarInfo, only one TclVoiceMail, only one EchoLink access and so on. You have to disable or comment out all announces caused by dmtf commands like "connecting to" or "wrong command".

If you disconnect the featured station from the link a network of dumb repeater remain since it doesn't have the "extended" module configuration and are clear of the most announcements!

I couldn't imagine that it is what you want.

Maybe it would be better to put more intelligence into the svxreflector later (e.g. EchoLink, Metar, DMR). But then you have to switch the provided functions between connected/disconnected state on all single nodes. I think it is not easy to answer this topic with a simple "yes" or "no".

vy 73s de Adi / DL1HRC

**Comment by gicardous** [comment]
Hi,
Our network in YO has over 40 nodes and growing; svxreflector solved problems like re-encoding  and voter crush.
But we do loose important features like restricted access (now everyone can connect and involuntary can cause trouble), the ability to temporary block some node to transmit in the network for good reasons like interference until problem is solved (but to transmit from the network), and the ability to display on the map which node is on.
I hope that future releases will solve that. Of course those first 2 can be done through firewall but I think it would be nice to be part o f the software.
Also the penalty timer would be nice to be manageable through config.

73's and all the best from Catalin YO7GQZ

**Comment by f5vmr** [comment]
Good day, Having today re-established our repeater network after a power outage, I noticed that the repeaters were reporting errors due to incompatible message protocol - repeaters were using 0.5 and the server 0.1. Not knowing what this means I downloaded and install the same version of svxlink (svxflector branch) on the PC and the repeaters and restarted the network. This is now the error that is generated from the repeaters:
Sat Jul  1 11:23:01 2017: *** WARNING[ReflectorLogic]: Unknown protocol message received: msg_type=0.

Similarly the server is reporting a heartbeat timeout, despite appearing to connect successfully to both repeaters before disconnecting due to this timeout. The repeaters continue to report as above.
Any ideas where this might be caused?

No faults were reported during the compilation and otherwise the systems work well. The server is running Ubuntu Mate 16.04.01 and the both Raspberries (one a pi2 and the other a Pi b+) are running the very latest versions of their operating systems.

**Comment by sm0svx** [comment]
Reflector users are now specified like this in the svxreflector.conf configuration file.
```
[USERS]
SM0ABC-1=MyNodes
SM0ABC-2=MyNodes
SM3XYZ=SM3XYZ

[PASSWORDS]
MyNodes="Change this key now!"
SM3XYZ="A strong password"
```
The GLOBAL/AUTH_KEY variable have been removed.

**Comment by sp2ong** [comment]
Hi Tobias,

I have switched to the new version of svxreflector with the new management of users and password. All working OK and nice idea to create separate passwords for groups or users. I have checked this and working without problems.

I have maybe one idea more about bridge svxreflectors. We have connected to local svxreflector small group local echolink nodes to create local virtual network voice communications. But we have idea to use this infrastructure to communication with EmCom. It will be a nice idea to have possibility create in svxreflector.conf setup to bridge with other svxreflector in another area where exist similar solution like we have. During a time when we use our infrastructure in EmCom and we need expand the area to communication to neighbor local infrastructure base on svxreflector we would like to make a bridge between our svxreflectro to neighbor svxreflectror. 

I know that I can do this by adding one more definition reflectorlogic in one node to connect to other svxreflector but maybe better solution will be when we make bridge between svxreflectors servers 

73 Waldek SP2ONG

**Comment by sm0svx** [comment]
As you can see in [the comment above](#issuecomment-286528059) there are some more features planned but the first step is to get the reflector into the master branch and do a new release.

**Comment by sp2ong** [comment]
Tobias,

Ok no problem. It only my idea and maybe we can discuss that it good idea or not add this to svxreflector
Thank you for new updates and I have updated my svxreflector to the latest version.

73 Waldek

**Comment by f5vmr** [comment]
I am confused. With the new password configuration in svxreflector.conf, how does this correlate with the AUTH_KEY="######" which is still in the client svxlink.conf? I am getting a TCP error reported. Have I missed something? I have updated my server and the repeater with the same method and package.

**Comment by sp2ong** [comment]
From client side don't  need a change in svxlink.conf in ReflectorLogic. In need have in svxlink.conf
in [RefelctorLogic] AUTH_KEY=

when use new version svxreflector on you need a change in svxreflector.conf

remove in [GLOBAL] AUTH_KEY=

and add new two sections

[USERS]
SM0ABC-1=MyNodes
SM0ABC-2=MyNodes
SM3XYZ=SM3XYZ

[PASSWORDS]
# password for all users which belong to MyNodes defined in [USERS]
MyNodes="Change this key now!"
# password for user SM3XYZ
SM3XYZ="A strong password"

**Comment by f5vmr** [comment]
All understood, but that does not solve this litlle teaser.
Client 192.168.0.105:50810 connected
192.168.0.105:50810 ERROR: Unpacking failed for TCP message header
Any ideas please

**Comment by f5vmr** [comment]
Thanks for that - It seemed that the first make install failed. The second attempt installed the failed library sections correctly. All now works as it should

**Comment by sm0svx** [comment]
Protocol change again but this time it should be possible to upgrade the reflector server first and then the clients one by one without service interruption. The server support both the old protocol version (0.6) and the new version (0.7) in parallel.

It is important to upgrade the server first since the server cannot support clients speaking a newer protocol version than the server do.

**Comment by sp2ong** [comment]
Hi Tobias,
Today I have seen that now svxreflector is in branch master and now I don't need a switch to branch svxreflector ?

73 Waldek

**Comment by sm0svx** [comment]
The svxreflector branch is now obsolete since the PR have now been merged. I'm going to delete it soon. Everything is in the master branch so you can switch back to that now (**git checkout master**).

**Pull request merged**
