### PR TITLE
Svxserver

### PR DESCRIPTION
**Pull request by dl1hrc**
Hi Tobias,

here is my first version of a stand allone server (svxserver 0.0.0.1-pre-alpha, hi ). It can connect different SvxLink instances together via LogicLinking out of EchoLink.
It's running for a while on at least six instances and connects up to ten stations in DL.
I know that it must be improved (squelch handling) so it would be nice if you can take a look into the code to give me some hints.

vy 73's de Adi, DL1HRC

### CODE REVIEW

**Comment by sm0svx** [comment]
OK, Adi. Just looked at the patch briefly. Initial comments:
* Remove Makefile, Makefile.default and makefile.dirs. These files was used by the old buildsystem which has now been removed.
* It's minimal changes outside of the svxserver directory, which is good. This will make it easier to accept the patch. This is not the way I imagined that nodes would be connected together but since the patch is pretty much isolated from the rest of the code I see no reason why it couldn't co-exist with any future solutions. And also, this is the only solution right now so it't the best one :-)
* You mention EchoLink in your initial comment but you seem to have based your code on RemoteTrx. Was it just a typo I guess?

Can you please describe to me in words how the concept work so that I don't have to figure this out from the source code. You also mentioned a problem with squelch handling. Can you elaborate on that as well?

**Comment by sm0svx** [comment]
And also, try to write good commit messages (e.g. no initial star on the summary line as we did with Subversion). This is the recommendation from the [Contributing to a Project chapter](http://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) in the [Pro Git Book](http://git-scm.com/book/en/v2):
```
Short (50 chars or less) summary of changes

More detailed explanatory text, if necessary.  Wrap it to
about 72 characters or so.  In some contexts, the first
line is treated as the subject of an email and the rest of
the text as the body.  The blank line separating the
summary from the body is critical (unless you omit the body
entirely); tools like rebase can get confused if you run
the two together.

Further paragraphs come after blank lines.

  - Bullet points are okay, too

  - Typically a hyphen or asterisk is used for the bullet,
    preceded by a single space, with blank lines in
    between, but conventions vary here
```
Later, when trying to debug something, it is important that the commit messages are easy to follow. A comment like "some smaller changes" does not say anything. Do a "git log" to get an impression of what it should look like.

**Comment by dl1hrc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am 21.02.2015 um 11:02 schrieb Tobias Blomberg:
> OK, Adi. Just looked at the patch briefly. Initial comments:
> 
> * Remove Makefile, Makefile.default and makefile.dirs. These files
> was used by the old buildsystem which has now been removed. * It's
> minimal changes outside of the svxserver directory, which is good.
> This will make it easier to accept the patch. This is not the way I
> imagined that nodes would be connected together but since the patch
> is pretty much isolated from the rest of the code I see no reason
> why it couldn't co-exist with any future solutions. And also, this
> is the only solution right now so it't the best one :-) * You
> mention EchoLink in your initial comment but you seem to have based
> your code on RemoteTrx. Was it just a typo I guess?
> 
> Can you please describe to me in words how the concept work so that
> I don't have to figure this out from the source code. You also
> mentioned a problem with squelch handling. Can you elaborate on
> that as well?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/sm0svx/svxlink/pull/129#issuecomment-75364866>.
>
> 
Hi Tobias,

yes it was my intension to let the svxlink-source at it is an build an
extension on the provided svxlink-interfaces.

The idea of the svxserver is to create a small network of
svxlink-stations that can be connected together out of the
Echolink-module. It can be used in isolated networks (hamnet) without
connection to the internet (e.g. no access to the echolink direktory).
Until now it was only be possible with one svxlink node and N
remotetrx's with the known disadvantages (missing control on remotes
when networkconnection is lost).
On "normal" nodes with internet connection it's now possible to have
EchoLink on all stations.
At the moment we have three nets running (possible more), the biggest
is here in East Germany with temporary up to 9 svxlink nodes.
There is an interesting project planned by Christian/DJ9PH to create a
svxlink network based on svxserver especially for young om's. The
nodes are build mostly with Raspi/BannanaPi to keep the costs low.

The configuration for a connection to the svxlink server is as well as
to a remotetrx since it is compatilbe. So it makes no difference if
you have one remotetrx connected to your svxlink node or if you have a
connection to the svxserver.
You have to configure two logics, the "normal" rf-logic and a
netlogic. The netlogic ist always connected to the svxlink server but
the audiopath between rf-logic and netlogic is controllable with commands.
So it takes only some milliseconds to connect eachother.

The svxserver just sends the commands of the NetTrxMsg-Protocol
received from one station to all connected stations so the audiostream
from one svxlink node is routed to all stations if the audio path is
connected by LogicLinking commands.

It should not replace the normal echolink network but I think an other
way to chaining stations together could be nice ;-)
I know, that this way has some problems and is not optimal. I see it
as a intermediate step on the way to an own svxlink-2-svxlink
connection protocol.

vy 73's de Adi, DL1HRC


-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEbBAEBAgAGBQJU6bLNAAoJEIBzxqy+/CmtaQkH9jKrK23cu2T9GKHN/hM1AOYl
QRK1h4WK0zYNZpQV6VBi+CTfu+2sHE5SYIJWsiIbLPUCXBe6D6EskuzAVMH3h3tv
1qPTbzz/lZgocjoVOJAskX82DD8fkPKvIj903OOwBPqoY0vmushAfoFN4ZDIhYnb
/JuZlfxF8ZJzPCT9xrQRv1+H03T04T/N81ezUjBAxi1aOtIu+0uIvp7GGkyPg8Li
CuJiNb4R7tnSjOGNeKknVNtBvUCG4JSck/GFeEz4INV6PxBmZ8vyZr0Mvq6cB64j
uQaorv3bcsGEbE7jpcYXKd5AEBhO/W6rT9zFxgHZKbDNsszmIm3VkiWB5/wZkg==
=83o6
-----END PGP SIGNATURE-----

**Comment by dl1hrc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am 21.02.2015 um 11:02 schrieb Tobias Blomberg:
> You also mentioned a problem with squelch handling. Can you
> elaborate on that as well?


Yes, the problem is if the squelch has been opened by an other station
and the network connection is lost then the local station remain on
the last received state (SQL=open, TX maybe ON).
There should be a reset in the case of lost network. But at the moment
I do not have a good idea.

vy 73s de Adi, DL1HRC

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJU6zkJAAoJEIBzxqy+/Cmtr1cH/3PyjfTq1PmL4yM5d76mY3YQ
oDuo4S1X6HpY/+y1pFIlNYYM4nwbsaeV1gxhQxGKUiEEOUH+t84kGsOhc/OBc97m
Pisb5ySUiGYUyDEfo0c3aaoKSKsrK6gA/0Wu/nIiZZHSvKaBA8D38FEm3gBoJE4K
PVHSHMKB8Bh833a8NjBCZ50DWn9fP/saznFHQuf8CfAuJpBFLdoSNEDisxiGeku9
N+AtWd27evnSAo6AxhLQ3WRvzLgVPMCldV+GfisWIsoH6b43JP31SEpJ6J/A507B
n+a9vn5O9Ju4FBA7rDte3SqGbWwXnCpi0BtOOT8Nkb897Sv7hIwkAPjOCimJny8=
=2hXj
-----END PGP SIGNATURE-----

**Comment by sm0svx** [comment]
I still cannot understand why the EchoLink module should be involved. If you are planning to remote control the svxserver through a module it would be better to write a module that is dedicated for that, but maybe there is something I don't understand.

Solving the problem with the squelch handling seem straight forward as well. When you get a TCP disconnection, set squelch closed and tx off repectively. The RemoteTrx protocol should already work like that. When the connection is reestablished, the correct state should be resumed.

**Comment by dl1hrc** [comment]
Hi Tobias,

I don't want to _control_ something by a module. The idea is just to connect different SvxLink instances (here audio streams) on an easy way. I would like to have all modules available on all sites and would like to be connected eachother out of any module. It should increase the range of a "virtual" repeater. If your'e located in city 1 there should be an easy way to talk to a friends repeater in city 2 without searching for el-numbers, waiting for connects....

<i>I still cannot understand why the EchoLink module should be involved.</i>

We are some repeater sysops working together in a loose way. Everybody want to have it's own SvxLink node with alle modules including EchoLink, LocationInfo and so on. There shouln't be any dependency from the installation of others as it is needed by a SvxLink<->remotetrx installation. The setup of a connection to a "friends" repeater shouldn't take up to 10 seconds like on EchoLink calls.
PropagationInformation should be locationspecific for each repeater as well as the MetarInfo.
I'm not sure if you can understand my idea at the moment, maybe that it's still not clear. I made a pic, please look here: http://svxlink.de/download/friends_repeater_system.pdf

73's de Adi, DL1HRC

**Comment by sm0svx** [comment]
Wouldn't the "force core command" feature solve your problem?  That is, prefix the link setup command with a star (*). If any module is active you can issue the following command to activate the link to svxserver:
```
*341
```

**Comment by dl1hrc** [comment]
Tobias, I'm not sure if we're talking about the same thing. The way of how to connect the nodes is secondary. In my opinion the primary thing is to have a simple connection between different SvxLink nodes out of echolink e.g. for the case that you have an internal network only.

Ok, step-by-step:
1) How do you want to make connections repeater<->repeater at the moment for the case that you only have a hamnet-network and you do not want to use internet services like echolink directory or only have one gateway between inet and your private network?
2) If you create one SvxLink instance and 10 remotetrx's (the only way at the moment), how you want to keep a normal repeater functionality alive (identification every 10 minutes, tx tailing, roger beeps, dtmf controls) for the case the SvxLink instance is down or the network connection to this station is lost? Yes, I know: sending pings every 10 seconds, if not responding stopping remotetrx, starting svxlink, sending pings, if alive again stopping svxlink, restarting remotetrx...but I think it could be done more intelligent, isn't it ;-)

Please let us start with this two points, ok?

73s de Adi, DL1HRC

**Comment by sm0svx** [comment]
I think we have a bit of a language problem here but I think I understand what you are trying to say now. We are talking about different things. What threw me off the track was your sentence "can be connected out of the EchoLink module". I interpreted this as "want to create connections to svxserver using the EchoLink module" while I think what you meant to say was "create connections between svxlink stations when EchoLink service is not available". Am I getting on the right track now?

Your idea is to use the RemoteTrx functionality to connect multiple stations through a central point, creating sort of a virtual radio channel between the svxlink systems. Correct?

You configure an extra logic that connect to svxserver. Then you can connect and disconnect from the svxserver "group" by activating and deactivating the link to the extra logic through the normal logic linking mechanism. Correct?

**Comment by dl1hrc** [comment]
Hi Tobias,

yes, everything you sad is correct and I think it's more my language problem than yours. Sorry for the confusion.
We have already running three different nets. Svxserver is working three times on a central root server as different instances on different ports.  I can send you the ip, port number and auth code if you want to connect to. But I guess there talking German only ;-)

73s de Adi, DL1HRC

**Comment by dj9ph** [comment]
Hi Tobias,

my name is Christian (DJ9PH), my son's name is Tristan (DO1TRI). He is 11 years old and licenced since 1 year now.
We use SvxServer to fixly connect several repeaters in regions with youth activities.
Exactly that is what Adi means, that there is a system easy to use and easy to connect permanently several repeaters worldwide, e.g. youth repeaters.
This way the kids can call CQ and for sure will have an answer from other kids throughout Germany. We also will use this repeater network for Kids Days, YHOTA and for training.
Later it would even be possible if there is a server in the states with several connected repeaters and one in Germany to connect via dtmf to the repeter network in the states. Then the kids can practice their english on an easy way.
We thought about the following setup:
1. network in Germany permanently connected, possible to disconnect for local QSO, after a specified timeout without activity the repeater will automatically reconnect into the German network
2. network other (e.g. USA): connect to the network with DTMF, after a specified timeout automatically disconnect to the second network.
That are our plans, which we want to realize OUTSIDE of the EchoLink features.
This way all local announcements (propagation monitor, local messages) keep local and are not sent via the network.
Anyway: Thanks a lot for SvxLink! That helps us a lot with getting young people on the air and it enables those youth groups to build their own repeaters.

73, Christian (DJ9PH)

**Comment by sm0svx** [comment]
You can actually achieve functionality something like svxserver with a specially tailored configuration for remotetrx.
```
[GLOBAL]
TRXS=LinkTrx

[LinkTrx]
TYPE=RF
RX=LinkTrxVoter
TX=LinkTrxMultiTx
UPLINK_TX=NONE
UPLINK_RX=NONE
LOOP_RX_TO_TX=1

[LinkTrxVoter]
TYPE=Voter
RECEIVERS=LinkStation1,LinkStation2,LinkStation3

[LinkTrxMultiTx]
TYPE=Multi
TRANSMITTERS=LinkStation1,LinkStation2,LinkStation3

[LinkStation1]
TYPE=NetTrxAdapter
LISTEN_PORT=5211
AUTH_KEY="Station1Password"

[LinkStation2]
TYPE=NetTrxAdapter
LISTEN_PORT=5212
AUTH_KEY="Station2Password"

[LinkStation3]
TYPE=NetTrxAdapter
LISTEN_PORT=5213
AUTH_KEY="Station3Password"
```
It's a bit contrieved but seem to work. Of course, each remote station need to get its own port defined. The TCP port number becomes sort of the user ID and the password is used to authorize access to that TCP port. This will work fairly well for a small number of stations.

The existence of the RemoteTrx solution raise some questions:

* Is is worth the effort to write a specially crafted application that only improve existing technology slightly?
* Is it worth the effort since this is just an intermediate solution?
* Wouldn't it be better to put in time in getting to the final solution?

**Comment by sm0svx** [comment]
Although the squelch handling seem to be buggy in the current NetTrxAdapter/RemoteTrx implementation, but that should be fixed no matter what.

**Comment by dl1hrc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am 01.03.2015 um 11:37 schrieb Tobias Blomberg:
> You can actually achieve functionality something like svxserver
> with a specially tailored configuration for remotetrx.
> 
> |[GLOBAL] [LinkStation3] TYPE=NetTrxAdapter LISTEN_PORT=5213 
> AUTH_KEY="Station3Password" |
> 


Yes this is known but it has some disadvantages in my opinion.

1) If the central base is out of work, all functionality on all
stations is lost. There is no identification anymore, this may cause
some problems and may be in conflict with the regulations. I can not
listen 24/7/365 on all of my stations to recognize this problem.

2) With the remotetrx-solution and a central base the
base-administrator decides which stations are connected and which one
not. He is the only one who has an influence on the configuration.

3) EchoLink and LocationInfo is possible only for one site (maybe two
with proxy), not all. So the other remote-stations are not found on
e.g. aprs.fi.

With the svxserver anybody can decide which network he wants to join
(if he know the authkey and port + ip) without interaction of the base
sysop.

Yes all of them can be made by external scripts but I would prefer an
simple all-in-one solution.

vy 73s de Adi, DL1HRC

> It's a bit contrieved but seem to work. Of course, each remote
> station need to get its own port defined. The TCP port number
> becomes sort of the user ID and the password is used to authorize
> access to that TCP port. This will work fairly well for a small
> number of stations.
> 
> The existence of the RemoteTrx solution raise some questions:
> 
> * Is is worth the effort to write a specially crafted application
> that only improve existing technology slightly? * Is it worth the
> effort since this is just an intermediate solution? * Wouldn't it
> be better to put in time in getting to the final solution?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/sm0svx/svxlink/pull/129#issuecomment-76591367>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJU8v1pAAoJEIBzxqy+/CmtkiUIAMJxIzsP392+DT/SoqHWMhzZ
4dnOk88SjJC0yx4RB1mXJX84Vw3bKUhPoKvK9chptUcAZ2EnAw9acUuhJEx1Gsfo
/xn6KhAQOskFo0uzZB2Dg80n2kWgZLDFlWmP0IxedgS2kCugq2hXXhJuqjPBY/l8
6TTcYbgUdv29z44cTJJVRpmAI0FB8rAqM/kKGkgYb9VlqZEwDLsZOgfsgXwHrLmO
2ZsF575sUEV/tNVKxWIvr+jtDQSqNN6oRTintd+LD4Q2LNHOVFCc+dY3ymPEdG/w
9vrkCcckxlNJGUVlAwRz+fnNGTzWVMDVpKV9PoYo9ZpF2wEO1yYRpOmgBm0IFIg=
=CzQf
-----END PGP SIGNATURE-----

**Comment by dl1hrc** [comment]
Yes, it's still not stable at the moment, will work on it next time.

**Comment by sm0svx** [comment]
Adi, I think you misunderstand the intention of the suggested RemoteTrx configuration above. RemoteTrx is used as the central point in the same way as svxserver is. All svxlink nodes is independent from each other, just like you want. RemoteTrx is only used to interconnect the svxlink nodes, not to manage transmitters and receivers.

I agree it's a strange use-case for RemoteTrx but the functionality is there already, ready to use without any software modifications.

**Comment by dl1hrc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

ok, I see it is possible with a more or less complex remotetrx
configuration. There are some remaining problems (maybe only for me).

1) The configuration is very rigid, no chance to connect for
additional stations on an easy way without sysop interaction. The
configured connections are a _must_, producing error messages if not
established. I see the connects from others as _dynamical/optional_.

2) Any station need an own port

3) Remotetrx-version as the base means it is trying to connect all
configured stations, these are incoming connections for each station
that can be made some problems with firewalls and the readiness of the
sysops (e.g. universities, qrl's).

As I sad a couple of days ago I see it as a first step for a svx-2-svx
protocol. I would like to implement chatrooms into the server so that
external nodes can connect e.g. 341# -> chatroom 1, 342# -> chatroom2
and so on. Another topic should be the switch from TCP to UDP for the
audio stream.
But I wanted to start with smaller changes that can be used step by
step, not everything at once.

73s de Adi, DL1HRC


Am 01.03.2015 um 13:59 schrieb Tobias Blomberg:
> Adi, I think you misunderstand the intention of the suggested
> RemoteTrx configuration above. RemoteTrx is used as the central
> point in the same way as svxserver is. All svxlink nodes is
> independent from each other, just like you want. RemoteTrx is only
> used to interconnect the svxlink nodes, not to manage transmitters
> and receivers.
> 
> I agree it's a strange use-case for RemoteTrx but the functionality
> is there already, ready to use without any software modifications.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/sm0svx/svxlink/pull/129#issuecomment-76595712>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJU8y5hAAoJEIBzxqy+/CmtowYIAMR35uIInscFEMrqFkJJ/oZt
48MkPWpkVvg/GddWVNY+6oVhGiXVOzx3yfBK0RVHz3Z0dXNKirYQuzb4hUjeR3Rh
VCt9WKIA1Aic0YSBKf6R4RgVCirnz7lr+vge55XYVfdpLQxfgPGtGG9yYYQ7jCDS
pVIQ1EZkHQ54hCbXh/Dlx7FiDOskkv6slIpmqcVi3xIGYZQnCjXxvtb2uiWZzKrR
I4oOUkPf/vSzpzBcieKo3vA4iXDJS4zByCtPkzsuP1oBuyhIoS+Zp6SOYUW6VTtn
J9MTkb9HlDcvxABXBoDehYsmmhPrmeC9Einvhelb1QTPKBaOYw8AS9ICRv8eAto=
=XQPy
-----END PGP SIGNATURE-----

**Comment by kb3vgw** [comment]
added to the 16.0-dev and tested

**Comment by sm0svx** [comment]
So now it's finally merged. I moved it to the new contrib directory though, like we discussed the last time around. I also removed the change in NetTrxMsg.h since the RemoteCall message is not an obvious attribute of a transceiver. Maybe it could be but it did not seem to be in use anyway.

**Comment by dl1hrc** [comment]
Hi Tobias,
thank you very much for adding into trunk.
Since I have a lot of new ideas regarding to svxserver there maybe the need to extend the NetTrxMsg protocol of some additional tcp messages. It would affect the remotetrx's too.
Do you see the chance to realize it even though not all of them are interesting for the remotetrx's?
E.g.: The RemoteCall transmission is really important for the case that some stand alone nodes are connected and the ip addresses are changing often. For the remotetrx's isnt interesting since the sysop is the admin for all of them in almost any case.
vy 73s de Adi / DL1HRC

**Comment by sm0svx** [comment]
I would not accept changes to the RemoteTrx protocol that is not Trx related. Also, such changes would probably affect not only the protocol but the whole abstraction of the transceiver API. It is simply the wrong place to implement the functionality that you want. You need to find another solution, like something based on a logic core or module, but this PR is not the place to discuss that solution.

I suggest that you create a new issue describing the functionality that you want. I think I have a pretty good idea what you want from the discussion above but I think it would be good to start fresh with a clear definition of the problem. Also, your vision may have changed since this PR was created.

**Pull request merged**
