### PR TITLE
Add playDtmf functionality (sending dtmf tones with/from tcl)

### PR DESCRIPTION
**Pull request by dl1hrc**
Hi Tobias,

I've added the functionality to send dtmf tones in the tcl-environment with the new playDtmf-function. I feel it would be better to use a DtmfEncoder-instance in the MsgHandler-class instead of DtmfQueueItem::readSamples to avoid redundancies. What do you think?

vy 73s Adi/DL1HRC

### CODE REVIEW

**Comment by sm0svx** [comment]
I feel the best solution would be to use the sendDtmf function already present in the Logic class which use the sendDtmf function in the Tx class.

*Pros:*
* Reusing current DTMF encoder
* Will mute other audio when sending DTMF
* Will generate the DTMF tones at the transmitter when using RemoteTrx which makes them cleaner than if they have been passed through an audio encoder (like speex, opus, GSM etc)

*Cons:*
* Will not work out of the box with other uses of the EventHandler, like in the EchoLink module. However, the EchoLink protocol have specific support for transporting DTMF digits and the correct way would be to implement a sendDtmf function that use this. The protocol support for this is not currently implemented in EchoLib though.
* The current sendDtmf function does not support setting duration and amplitude on the fly but is rather configured in the LocalTx configuration. This could be implemented but the RemoteTrx protocol would have to be changed then (which is no major problem).

**Comment by dl1hrc** [comment]
I've changed the code according to your hints. Now the dtmf encoder in the Logic class is used. The NetTrxMsg protocol has been changed to make them available for remote TX's.

**Comment by sm0svx** [comment]
Unfortunately your last commits messed up the pull request totally. Please clean it up.

Do you really need to set the DTMF duration and level from TCL?  Wouldn't it be possible to stick with the current approach of setting it in the tx config? Then the patch will be much simpler. In my comment above I didn't mean that you had to implement the Tx changes but rather presented it as a possibility.

I'm asking because I mostly are trying to get SvxLink stable for the next release and a simple patch I can easily merge to master but a more complicated one would have to wait until after the release.

**Comment by dl1hrc** [comment]
Hi Tobias,

*grrr* this was only one missing checked checkbox in codeblocks :( I've
reworked it, thinking the code ist now clear of changed spaces. On the
other hand, please could you explain the functionality of additional
spaces in blank lines or tailing spaces after a "}"?
I think additional functionality (configuration of tone duration and
power) maybe always good :) You can find the same options for the
playTone function. If you want I can remove this feature for now but I'm
sure I will get feature request to put them again in the source code
soon. Do you see some problems with two additional parameters when
sending as netmessage to remote-TX's?

vy 73s de Adi, DL1HRC

Am 11.10.2015 um 09:52 schrieb Tobias Blomberg:

**Comment by sm0svx** [comment]
There is no functionality in trailing spaces and normally it's a good thing to remove them. However, now they're there and removing them may cause more harm than good. Have a look at the [updated contribution documentation](https://github.com/sm0svx/svxlink/wiki/ContributingCode#create-a-pull-request) for an explanation. In parts that you have edited or in new code, of course you should strip trailing spaces.

Anyway, the code looks much better now. I have not had time to study it deeply but I had a quick look. I'm trying to convert all levels into dB power instead of using some percent level value like I did before. I saw you had some defaults of 300 and 400 somewhere and since 0dB is a full scale value 400dB is a little bit over the edge :-)

Also make sure variables are named to reflect that it's a power value and not an amplitude value. You have used digit_pwr (correct) in most places and amp (incorrect) in other places. The name tone_pwr is also a bit misleading since there are two tones. One might be mislead to think that it's the power for each tone that is set when in reality it's the total power for both tones, the whole digit, that is set. That's why I think that digit_pwr is the best choice.

And no, I don't think you should revert what you have done. I'll just won't merge it before the release but hopefully I'm pretty close to making a release now.

**Comment by dl1hrc** [comment]
Am 01.11.2015 um 20:36 schrieb Tobias Blomberg:

> Anyway, the code looks much better now. I have not had time to study it deeply but I had a quick look. I'm trying to convert all levels into dB power instead of using some percent level value like I
> did before. I saw you had some defaults of 300 and 400 somewhere and since 0dB is a full scale value 400dB is a little bit over the edge :-)
> 

Yes, it was a bit irritating to use a values from 0 to 1000 for the tone (playTone procedure) and a dB value for dtmf. But ok, if it is known there is no problem.

> Also make sure variables are named to reflect that it's a power value and not an amplitude value. You have used digit_pwr (correct) in most places and amp (incorrect) in other places. The name
> tone_pwr is also a bit misleading since there are two tones. One might be mislead to think that it's the power for each tone that is set when in reality it's the total power for both tones, the whole
> digit, that is set. That's why I think that digit_pwr is the best choice.
> 
> And no, I don't think you should revert what you have done. I'll just won't merge it before the release but hopefully I'm pretty close to making a release now.
> 

Please do not merge it at the moment, there is a fundamental problem I think:
The tone generation initiated by playTone (tcl) is made in the MsgHandler-class, it contains it's own tone generator. If you implement the playDtmf procedure
this way you have some redundancies. It's working but it isn't a good way I think.
The other worse thing is if you have some TX's connected (MultiTx) over the network possible using some encoders (speex, gsm,...) the signal will
be "encoded" by that codecs.
The better way would be to create all tone, dtmf, afsk,... -functionality in the LocalTx-class and remoteTRX's, isn't it?

BUT: If you use the tone generator (and my new implemented dtmf-encoder) in the Tx class you will get another problem.
Since the playTone/playDtmf commands are not put into the item queue (MsgHandler::addItemToQueue(item)) you're facing unwanted results.
Frank/DL7ATA reported that the playDtmf command was executed successfully but the following tcl-commands like playTone, ZVEI::play "xxx"
not (no tones, no ZVEI-SelCall, no error's).

Could you give me a hint how I can synchronize the tcl-queue and the local created audio? Is it better to send all wanted output to the TX's
and put more functionality into the TX-class?

vy 73s de Adi, DL1HRC

**Comment by sm0svx** [comment]
I think we need to take a step back.

The TCL event handling system was introduced to make it easy to adapt announcements to different languages. It is basically made to emit different forms of sounds that is meant for the human ear and not meant to be decoded by a machine. You seem to be wanting to add functionality in TCL, which was not the intention from the beginning. That may be OK for simpler sequences like playing a string of DTMF digits but when you start combining that with normal announcements you start getting into trouble.

I don't want to move all announcements to the RemoteTrx side because that would mean that the sound clips have to be available on each RemoteTrx, which feels like a mess.

Maybe it would be possible to do some form of synchronization between event sounds and things like DTMF, AFSK etc but I feel it's probably hard to enforce the order of transmission. As it is implemented right now, I think normal sound will be thrown away while transmitting DTMF. We would get strange effects if holding the normal audio stream since we would get a big delay in the sound stream after a DTMF string has been transmitted.

Maybe it's better to after all use your original implementation. Synchronization will then work but we will get back the original problem with the DTMF being encoded by the audio encoder. If not compressing audio or using a higher bit rate codec maybe it will be good enough for what you want to do.

Maybe whatever you want to do should not be done in TCL at all?  Maybe it would be better implemented as a new feature in C++?  I cannot say since I don't know what you aim at doing.

**Comment by dl1hrc** [comment]
I reworked, should work now anyway. The idea is to provide the user the possibility to send dtmf digits on an easy way. At the moment there is now chance in SvxLink, the DtmfRepeater must be activated and is not event based (incoming/outgoing connections, SQL state, TX state, ...). 
Dtmf could be used as a selcall functionality or to control other stations when a special event on the own station has been occurred. In my opinion it should be easy be done by playDtmf "1234.."; in tcl since there are a lot of procedures you can use to generate it (EchoLink::remote_connected {}e.g.). 
At the moment you can generate a single tone or a ZVEI2 selcall very easy in the tcl environment but not two tones at the same time. This is not really comprehensible ;) I know, the structure in SvxLink is not optimal to do this at the moment especially if there are further ideas with aprs (afsk) and so on.

**Comment by sm0svx** [comment]
Still want this merged I guess?

**Pull request merged**
