### PR TITLE
file and install,  

### PR DESCRIPTION
**Pull request by km4eug**
I have downloaded file onto the rasber pi,  how do i install?  puzzled, and where can i get the most current file. looking to run eco link on rasbery pi 

KM4EUG

### CODE REVIEW

**Comment by f5vmr** [comment]
Hi,

Greetings from France,

Not so simple as a download of course. Look at the svxlink.org page and
click on the big icon on the right, that will take you to a major page of
information.

Once you get there look for material relating to installation. If you have
no previous knowledge of Linux, Debian or similar you make need to take a
steep learning curve.

 

I can talk you through it (I have skype) and we can see where you have got
to.

Regards

 

Chris F5VMR/G4NAB

**Comment by km4eug** [comment]
Chris,
Thank you for your reply. Have no knowledge of programing

Was under the understanding to down loan instal and zoom it works.

Guess I was fooled on that one.

Was really wanting a dedicated device for Eco link and it not having to be
another pc

Is the tar.gz file on line current.  Was reading where it may be way out of
date ?

Terry km4eug

**Comment by f5vmr** [comment]
Hi Terry,

 

It is fairly straight forward, but a bit daunting for the uninitiated. There
are down loadable complete images, but even they are temperamental.

It is a wonderful piece of kit for EchoLink, and works extremely well. I for
one find it beyond compare as the heart of a repeater (I look after several
here with 6 raspberries in the final network)

If you have a working image of Raspbian Jessie or Raspbian Wheezy and you
are working in the desktop or command line, It is simple to do if you
provided you keep track of all your method and file locations.

If you want a live chat, drop me your email and we can do that, and talk you
through it. You can have a working system in a couple of hours.

 

Regards

Chris f5vmr@orange.fr

**Comment by km4eug** [comment]
I am driving and not at shack at this time.
Km4eug@gmail.com

I will get a Skype account and see when we can move thru this.  Thank you
so much

Terry km4eug@gmail.com

**Comment by sm0svx** [comment]
This is not a pull request. Pull requests are for contributing code and not discussing support issues. For discussions, use the svxlink-devel mailing list. Have a look at the wiki for more information:

https://github.com/sm0svx/svxlink/wiki/GettingSupport

**Pull request closed without merging**
