### PR TITLE
Systemd for svxlink

### PR DESCRIPTION
**Pull request by kb3vgw**
adding systemd as a part of svxlink and enabling it by default at build time.

Moving away from init.d

Changes to main cmake file to add in the systemd build 

added the systemd dir with needed files.

Including the new gpio setup and teardown scripts

### CODE REVIEW

**Comment by sm0svx** [comment]
You have watchdog configured in your systemd files, shouldn't there be some code in the svxlink and remotetrx applications to support systemd watchdog?

**Comment by rneese45** [comment]
I moved the svxlink_gpio.conf.in and the Cmake for the svxlinkdir into this for installing the file as its really part of the new systemd

**Comment by rneese45** [comment]
I removed the unused watchdog code from the systemd code . this will allow for it to be commited into th main stream code now

**Comment by pe1chl** [comment]
Is it not possible to auto detect systemd and enable/disable the compilation option accordingly?

**Comment by kb3vgw** [comment]
The option is to support both init.d on older systems and system on new.
And I will n work on systems auto detect bu as I recall I thought it would
be enabled by default. As system is default init on most systems now

**Comment by pe1chl** [comment]
What does this "adding systemd as a part of svxlink" really mean?
Is it only providing some files that systemd will use and other environments will just ignore?
I am against dependency to systemd, we don't want systemd on our computers and I hope
that svxlink will work on init.d systems as before.  We have existing /etc/init.d/svxlink etc and
as long as they keep working everything is fine.

**Comment by kb3vgw** [comment]
It adds the files needed for the daemon to start n and stop svxlink
automatically.  It also includesnfi l es used for setting up and
configuring gpio pins for use with svxlink setup teardown on start and stop
of svxlink using the systemd  daemon. Also systemd  is is replacing init.d .

**Comment by pe1chl** [comment]
Ok...  please make sure the support for init.d remains there.  I don't want to start a
political discussion but we keep our systems as Poettering-free as possible.

**Comment by kb3vgw** [comment]
Init.d will be gone soon . They are pulling it out in the near future. Also
Debian pkgs require that pkgs move to systemd and away from init.d and pkgs
are in the works. I currently build and maintain arm pkgs

**Comment by pe1chl** [comment]
At first we moved from Ubuntu to Debian because of systemd, and next we will
move away from Debian.   Probably to Devuan.  We like freedom, not Poettering-control.
But let's end this discussion.  To each what they like.  As long as svxlink remains independent
from systemd.

**Comment by kb3vgw** [comment]
Well if u plan to use the new boards we made . And will be releasing once
the v1.1 boards are back . The plug on to the pi and c1 boards abs use the
systemd gpio setup scripts. And it is a full repeater board

**Pull request merged**
