### PR TITLE
Ability to change SvxReflector parameters on runtime

### PR DESCRIPTION
**Pull request by dl1hrc**
Introduce a new branch "reflector-ptyctrl" following an idea from Jens/DJ1JAY to change some SvxReflector parameters on runtime.
For special cases it would be useful if you could change certain parameters of the SvxReflector at runtime without having to restart it. The pseudo tty interface is an ideal approach in my opinion, not just for this case. Please check if this approach is acceptable when you have a chance, thank you.
Mni 73s de Adi / DL1HRC

### CODE REVIEW

**Comment by RichNeese** [comment]
Please rebuild your commit without all the branch merges. to make it a cleaner commit and easier to test

**Comment by dl1hrc** [comment]
I think it makes no sense to continue developing here, since extensions remain uncommented. Pull requests are also not considered and there is no discussion about further extensions. I'm thinking about deleting all my branch and going on to other things. It's a pity, but it probably can't be changed.
Mni 73s de Adi / DL1HRC

**Comment by RichNeese** [comment]
Well I don’t know what has happen but svxlink can be branded and we build a new system.  I think the last 2 years have made things hard.. I have been patching my own branch and testing… I am also orking on the guy openrepeater to try and get a updated build….


Th only other repeater out there is all start link and its even more out of date

**Comment by sm0svx** [comment]
New command structure implemented, similar to the one used in SvxLink server, so to set a config variable use: `CFG section tag value`. Example: `echo CFG GLOBAL SQL_TIMEOUT 500 > /dev/shm/svxreflector-cmd`.

**Comment by sm0svx** [comment]
Rebased and merged in commit 5636dffc96cc4819aa0ef358f0db222198e67a6f

**Pull request closed without merging**
