### PR TITLE
Qt5 update

### PR DESCRIPTION
**Pull request by rneese45**
this updates from qt4 to qt5

### CODE REVIEW

**Comment by sm0svx** [comment]
The en_US-heather subdirectory in the svxlink source repo was obsolete so I simply removed it, which solves the clone problem for that repository. The problem is still in the separate sound clip repository but that's another story.

I'd like to keep Qt4 support since the code changes does not conflict with that. I'm working on the CMake files right now.

**Comment by sm0svx** [comment]
Please test the new code in your source tree.
```
git checkout qt5-Update
git pull git://github.com/sm0svx/svxlink.git rneese45-qt5-Update
```
Push it if it works.

**Comment by rneese45** [comment]
did you want it pushed to master or just into my patch ?

**Comment by sm0svx** [comment]
Push it to your own branch. It's nice to have the pull reqest up to date. Especially since I need to hold off the merging until I have created a new release. I'm concentrating on eliminating bugs right now and I don't want to risk introducing new ones.

**Comment by rneese45** [comment]
OK. Well I am working on systemd now and adding in watchdog timer

r.e.neese

**Comment by sm0svx** [comment]
Now when the 15.11 release has been made I thought I would start merging some pull requests, starting with this one. Do you have any uncommitted changes for this branch?

**Comment by rneese45** [comment]
No no chanes

**Pull request merged**
