### PR TITLE
Service and webpage to demo eventsource mechanism.

### PR DESCRIPTION
**Pull request by pe1chl**
The file eventsource.pl is a service that reads the state PTY in
SvxLink and provides an EventSource that webbrowsers can connect
to retrieve Voter information and other events.

In the httpd directory an example webpage is given that displays
the information.

### CODE REVIEW

**Comment by sm0svx** [comment]
Please move the eventsource directory to src/svxlink/scripts/.

**Comment by sm0svx** [comment]
A README would be nice as well. Is it as simple as starting the perl script in the eventsource directory and everything will just work? Dependencies?

**Comment by pe1chl** [comment]
Ok I am still experimenting with github :-)
Indeed it needs a small document.  I also have an init.d script.

**Comment by pe1chl** [comment]
Is it now more like what you had in mind?
I wonder if you would want to put the publishStateEvent call in the default Logic.tcl or if this is
too specific for this particular feature and should be done in the local file by the user.
Same for other events that I might want to add in other tcl files.

**Comment by sm0svx** [comment]
Looks good and if you feel you are done with the PR at the moment I can probably merge it.

About adding the events; I think I'd rather add "standardized" events to the C++ code. I want to keep the TCL scripts as clean as possible. The publishStateEvent function should only be used as an easy way for users to add additional custom events.

**Comment by pe1chl** [comment]
Ok it is fine to merge it.   When putting events in the C++ code please note that the eventsource.pl
script assumes that single values are output as tag=value and value lists are output as
tag:value1:value2:value3
The script converts them to corresponding JSON or XML data structures for use by the webpage.
(I had prepared the second form for e.g. a list of connected echolink stations but it is not yet
output as an event because I noticed I would have to keep the list manually in TCL.  when it is
directly output from C++ this can be done much easier)
Of course other formats can be used in case the above does not match the requirements, but
then special handling has to be done in eventsource.pl, like for Voter:sql_state.

Am I right that adding the transmit event in C++ would mean adding

    ss << "tx=" << (is_transmitting ? "1" : "0");
    publishStateEvent("Logic:transmit", ss.str());

to the end of the function Logic::transmitterStateChange?
Or would you do that in another way?

**Comment by sm3sgp** [comment]
I am testing the eventsource and webpage example at SK3GW Repeater right now. Works nice!
There are some parts of the example files that is not in english, could it be possible to change those?
I am new to both the JSON data structures and most of the java/html, so any kind of extra comments and descriptions in the files helps!

**Comment by pe1chl** [comment]
Hi,
Yes I am aware that the text in the HTML page is sometimes in Dutch.
You can translate them to any language you like.
"Signaalwaardes bij" = Signal levels at
"Ontvanger" = Receiver
Some of the text is already in English.
Unfortunately there is no syntax to insert comments into JSON files!
When editing the JSON take note that there cannot be a comma after the last item in a list.
So always be careful when adding or deleting something.
The whole thing probably needs to be documented, but it actually is a bit of a work-in-progress,
it is easy to add items to the JSON for new features, and by far not all items are used by the
current example.

**Comment by pe1chl** [comment]
Some Dutch text on the webpage examples has been translated to English.

**Comment by sm0svx** [comment]
Did you commit your english translations to the correct branch (eventsource)?  Did you push your branch after committing? Your commit should have shown up on this page.

**Comment by pe1chl** [comment]
sorry I had forgotten the git push step, I am new to git.
now it sjould be OK.

**Comment by sm0svx** [comment]
> Am I right that adding the transmit event in C++ would mean adding
> ```
> ss << "tx=" << (is_transmitting ? "1" : "0");
> publishStateEvent("Logic:transmit", ss.str());
> ```
> to the end of the function Logic::transmitterStateChange?
> Or would you do that in another way?

There is no support for publishStateEvent in the TX base class as there are in the Rx base class so that have to be added first.

Also, I'm not 100% satisfied with the current format of the state event messages. But anyway, I'll merge this PR as-is and we can solve the formatting issues later.

**Comment by pe1chl** [comment]
Ok thanks!  Probably it is best to first experiment from TCL and see if it can be included in the C++
code later.  For usage in a web browser app we need a standard format that is easy to parse in
JavaScript, and the daemon offers both JSON and XML but the current software uses only JSON.
A possibility would be to drop XML and make the input to the publishStateEvent function directly
in JSON format, but that is less clear in the sourcecode and it is tricky to do the special handling
for certain fields like the timestamp.  But it surely is more versatile.
As it is now, the daemon can do the conversion from simple text data provided by SvxLink into
JSON without knowing about each type of message.  The sql info message is an exception
because it does not adhere to this format, and also because it conveys more information than is
possible in the format.

**Comment by pe1chl** [comment]
Thanks!

**Pull request merged**
