### PR TITLE
Adding config variables for CW playout

### PR DESCRIPTION
**Pull request by Dloranger**
changing the behavior of the CW function to use configuration variables
so they can be configured on a channel by channel basis.

Disables the ability to set them other places in the code such as
locale.tcl, code is left in place but commented out for easy reverting
for users who use custom logic overrides

### CODE REVIEW

**Comment by sm0svx** [comment]
This can be implemented without modifying the C++ code since any configuration variable is available in the TCL code as CFG_varname. So if you specify CW_AMP in the config you can access it as CFG_CW_AMP in the TCL code. E.g.:
```
variable Logic::CFG_CW_AMP
puts "### CW_AMP=$CFG_CW_AMP"
```
Also, I'd like to keep the possibility to set parameters in code. One way would be to implement a restoreDefaults function which can be called after changing prameters in code. The intention would be to change parameters for a single transmission, do the transmission and then restore parameters to the configured defaults. An example when this may be interesting is when using a receiver voter. The default implementation of send_rgr_sound will send the receiver ID using CW with other parameters than the default.

**Comment by Dloranger** [comment]
Have a look and let me know if this fits the model better

**Comment by sm0svx** [comment]
Yes, that was about what I was thinking of. It didn't work though but I have fixed it all now and merged the PR.

When I was at it I also changed the CW::setAmplitude function so that it takes a value in dBFS instead of thousands of full amplitude so -6 is about the same as 500. I also extended the CW::play function so that speed, pitch and amplitude can be set through optional function arguments.

Also added a CW_CPM configuration variable so that either CW_CPM or CW_WPM can be used.

**Comment by sm0svx** [comment]
And oh @Dloranger , you may have noticed that I had to use [::Logic::CFG_varname](https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/CW.tcl#L133-L136) (the :: prefix) to get it working. The same probably goes for your other PRs.

**Pull request merged**
