### PR TITLE
Add QT_ONLY option, fix qtel manpage install, and fix FindDL.cmake

### PR DESCRIPTION
**Pull request by W8BSD**
This adds a QT_ONLY option which uses the already installed async\* and echolib libraries and only builds the Qt library and qtel binary.  This was added so that svxlink and qtel could be separate ports without needing to rebuild the entire svxlink system twice.

Fix a minor nit where the qtel.1 manpage would be installed even when qtel itself isn't.

Add support in FindDL.cmake for systems which have dlopen() and friends in libc rather than in a separate libdl.

### CODE REVIEW

**Comment by sm0svx** [comment]
First, please next time create a branch for your patch. I forgot to tell you the last time.

I have been thinking of making parts of the build optional to be able to compile parts separately. I understand that the QT_ONLY option solve your problem but it's not what I would aim for. I'd like to have it split in BUILD_ASYNC (asynccore, asyncaudio and asynccpp), BUILD_ASYNC_QT (asyncqt), BUILD_ECHOLIB (echolib), BUILD_SVXLINK (svxlink, remotetrx etc) and BUILD_QTEL. For backwards compatibility the USE_QT option should set BUILD_ASYNC_QT and BUILD_QTEL. The rest of the options should default to TRUE.

**Comment by K6BSD** [comment]
Sorry, I'm not really a git users, so I'm not sure what "create a branch for your patch" means.  I thought K6BSD:master is a branch of sm0svx:master already.

I'll work on the options you've listed over the next week or two.

**Comment by sm0svx** [comment]
The Git terminology can be quite confusing at first :-)

K6BSD:master is a fork of sm0svx:master. A branch is something you create in your own fork. Just follow the guidelines on the [contributing code](https://github.com/sm0svx/svxlink/wiki/ContributingCode) page and you'll be fine. You will find how to create a branch on that page.

**Comment by kb3vgw** [comment]
working to add to the 16.0-dev branch

**Comment by sm0svx** [comment]
This PR have been sitting here for quite some time now. I'll close it for now. If you want to continue working on it either reopen it or create a new one. I don't know what's most convenient.

**Pull request closed without merging**
