### PR TITLE
Rename help_subcmd6*.txt to help_subcmd6.txt

### PR DESCRIPTION
**Pull request by rneese45**
fix file name to work with windows naming convention

### CODE REVIEW

**Comment by sm0svx** [comment]
Unfortunately it's not as easy as to just rename the file. You need to fix the [TCL function that play the subcommand help messages](https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/events.tcl#L35-L68). This function will expect the file name to contain the subcommand digit sequence. The 6* command will be presented as just "6" if the star is removed.

One solution would be to change the TCL function so that * is encoded as S and # is encoded as H. So the filename would then be help_subcmd6S.txt. The TCL function would then translate H to # and S to * before calling spellWord.

**Comment by rneese45** [comment]
OK that helps . and I will have to then split my fices into pulls.the
biggest fix is the update to qt5 . I have done a build n test with the
fixes . but working now to get systems stuff done. So we have proper deb
pkgs. I will work on the cutting up of the changes most where small clean
up. Like spelling errors found and marking off hyphen vs minus signs

r.e.neese

**Comment by rneese45** [comment]
If u change the function . I will pull and work to get the rest to u

r.e.neese

**Comment by sm0svx** [comment]
Remote branch has been deleted. Nothing to pull. Closing pull request.

**Pull request closed without merging**
