### PR TITLE
Build on Travis CI

### PR DESCRIPTION
**Pull request by george-hopkins**
To check whether new pull requests break the build, we could use Travis CI to check if the build succeeds. This way we would have a clean, reproducible build environment and an immediate feedback on contributions.

To enable Travis, simply [sign up](https://travis-ci.org/auth) and enable it for `sm0svx/svxlink`. Afterwards all new pull-requests are automatically built on Travis.

With the proposed configuration the project is tested with QT4 and QT5.

### CODE REVIEW

**Comment by sm0svx** [comment]
Interesting. I'll have a look at it.

**Comment by sm0svx** [comment]
I almost forgot, I actually already build SvxLink on the Drone.IO CI system.

https://drone.io/github.com/sm0svx/svxlink

Build number 21 was triggered after merging your pull request.

I don't know if there are any advantages to using Travis CI over Drone.IO but if it is as easy to get going as you say I might as well try it.

**Comment by sm0svx** [comment]
And oh, a binary archive for Debian for the latest build can be downloaded from

https://drone.io/github.com/sm0svx/svxlink/files

It's built to be unpacked in /opt. I don't know if it's of any use though. Just an experiment for now.

**Comment by george-hopkins** [comment]
Oh, I didn't know that there is already a CI system in place. By using Travis pull-requests would get tested too, this way you would get feedback before merging. You would probably have a bit less work as contributors automatically see that they break the build.

In addition the build status is directly shown next to the pull-request (e.g. as [seen here](https://github.com/twbs/bootstrap/pull/18518)).

**Pull request merged**
