### PR TITLE
16 0 dev

### PR DESCRIPTION
**Pull request by kb3vgw**
fully working updated build

### CODE REVIEW

**Comment by kb3vgw** [comment]
this covers commits #202 #193 #192 and #191 also it covers up alot of white space removal and general cleanup to shrink code and make it easier to read. This also includes systemd in the build

**Comment by kb3vgw** [comment]
in the 16.0-dev in systems we moved the gpio setup to /etc/svxlink/svxlink-gpio.conf
and added some new setup scripts that do the setup and tear down. Also added that svxlink waits for svxserver if enabled. so that svxserver would have to start thn svxlink would start up. Also updated the svxlink.conf.in to have lot more of the active functions including the sdr configuration and link radio configuration. this was all stuff we have tested for months and works with the repeater boards we have designed for svxlink wich is 2 that work on the pi 2/3 and odroid c1/c1+/c2 boards currently.

we added a remote relay control module and a few other modules and are working on more. the Metainfo module is also update. 

I have new and current sound files also that I paid for in a new name aas the old voice has been rm from the provider service. I have to finish the metainfo voice and update them. 

over all this has all ben tested and running for 4 months with no issues .

**Comment by sm0svx** [comment]
I'm sure there are some good things in this pull request. However, it's too big to be accepted. I like to look at each individual feature added and accept (or reject) them one by one.

Also, I never accept patches that unnecessarily change whitespace or formatting. Even though some changes may be good, they may make it harder to merge with other branches.

Contributions for Debian packaging should be done through the official Debian package maintainer, Felix Lechner (@lechner). I think [this is the main page](https://tracker.debian.org/pkg/svxlink) but I'm not sure (Felix?).

The original Acapela Box Heather US voice, that is currently used for SvxLink, actually is still there but it's only available after logging in.

**Comment by kb3vgw** [comment]
Well I paid b for the new sounds and we have them in french and english.
Most the commits are in this branch came from t g e different pull request.
The whitespace and formating was because the b c community said the wh I
tell d Pl ace and all the ******* in the code was ugly and they would not
help until it was cleaned up. The new modules and the NE svxlink.conf.in
has all the functions so people can see them.

**Comment by kb3vgw** [comment]
Also with u go so long and not commuting pulls we had no choice but to do
the pull request and test and confirm they work . So with rejecting the
cleanup and whitespace removal and the pull test on every pull on you sit
your rejecting all the tested work

**Comment by kb3vgw** [comment]
Lecher did pull my debian changes and my new scripts for systmd but I have
done updates. Also I have 4 more modules going in the code. Solar / power
monitoring /repeater emergency mode and 1 other that we have worked on to
go with the hardware we designed for svxlink. We have 2 arm based repeater
boards now. Fully tested. So I put in the time and money .

**Comment by sm0svx** [comment]
No problem with your sound packs. Heather will still be the default for now though. I'd be happy to accept your sound packs as contributions if you'd want that. I can create new projects in the [SvxLink GitHub group](https://github.com/svxlink) for each of your sound packs and give you commit access to them. It's up to you. Right now I havn't started using the SvxLink group but I have been meaning to do so.

Pull requests almost never can be accepted without change. That is why I need to go through each one. If it was as easy as just merging them I would have done it a long time ago myself. That everything is running fine on your system does not mean that everything is correct. It may just mean you have been lucky.

What's beautiful code and what's not is in the eye of the beholder I guess. I like most of it the way it is so changes in style will not be accepted unless coordinated with me first.

For sure it was a problem I was away for a long time and I understand that you needed to do something to push forward. It's unfortunate but it's just the way it is. I'll try to be a better maintainer.

My opinion is that you should contribute the Debian stuff to Felix's repository. I'm not anti-Debian or something. It's great that you are working on it. I just want everything to go through the official maintainer to reduce confusion. If necessary I could then accept PRs from Felix.

I'd be happy to accept pull requests for your new modules if everything is looking good.

**Comment by lechner** [comment]
Hi Richard,

First of all, hats off to you and your team for bringing so much positive
activity to the project! You worked tremendously hard on the code base to
support new hardware. Svxlink will become much better because of you.

The discussion you and Tobias have is quite common when an established
project meets a creative and disruptive force like your team. However, even
your patches will benefit from Tobias's review. They should be split by
feature, in the order in which you want them included, to give Tobias the
freedom to steer the project. I am convinced he will use that power wisely.

Some disappointments are sure to be on the way: Years ago, I spent two days
converting the build system from Tobias's homegrown system to autoconf
(which worked better for Debian packages). I had even obtained Tobias's
approval ahead of time. Tobias looked at my patch for a while. Then he
thought about his own requirements and picked CMake.

Sometimes the inclusion may also take time. I am still hoping for automake.
:)

With the amount of work you are contributing, I am sure Tobias will relax
his standards for the cleanliness of pull requests. He knows that
separating features is cumbersome and difficult. As for whitespace changes,
I have yet to find an upstream project that accepts them. The key here is
cooperation. Let's get as many of the new features included as possible!

Please remember, Richard, you can also send your patches to me. I do not
need Tobias's approval when I apply patches before shipping Debian packages
and usually maintain a small stack of them.

The same is true for the voices. I can include any and all voices. I can
even change the default for Debian, which many people use. On that note, I
still have the Heather and Elif sounds. They have been ready for four
years. I just have to read through the acapela license one more time. Where
can I find your sounds, please? Thank you!

Best regards,
Felix

**Comment by kb3vgw** [comment]
kill branch

**Pull request closed without merging**
